language: java
jdk: oraclejdk8
install: true
script: cp .travis-settings.xml $HOME/.m2/settings.xml && ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
    - $HOME/.m2

services:
  - docker